spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/url-shortener
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
shortener:
  base-url: https://misft.me
  charset: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  short-url-min-length: 3
  short-url-max-length: 6